[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan storage:unlink || true",
    "php artisan storage:link",
    "chmod -R 777 storage/",
    "chmod -R 777 public/",
    "chmod -R 777 bootstrap/cache/",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan optimize",
    "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8000} -t public"
